[profile.default]
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'forge-cache'
evm_version = 'london'
solc = '0.8.22'
optimizer_runs = 10_000

[fuzz]
runs = 1000

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
